# Generated by Django 2.0.6 on 2018-10-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktiviti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tajuk', models.CharField(max_length=255, verbose_name='Tajuk')),
                ('tempat', models.CharField(max_length=255, verbose_name='Tempat')),
                ('penceramah', models.CharField(max_length=255, verbose_name='Penceramah')),
                ('hadpeserta', models.CharField(max_length=255, verbose_name='Had Peserta')),
            ],
        ),
    ]
